all:
  stylesheets: ["/opGyoenKintaiPlugin/css/prettyPopin.css"]
  javascripts: ["http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.5.1.min.js","/opGyoenKintaiPlugin/js/jquery.prettyPopin.js","/opGyoenKintaiPlugin/js/kintaiedit.js","/opGyoenKintaiPlugin/js/kintaiquery.js"]

